### ISSUE TITLE
V2.2 JQuery not defined

### ISSUE THREAD

**Issue by MrRobboto** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#81]
So I'm using this bridge and just upgraded a new project to 2.2.  With the aurelia-skeleton-navigation typescript setup I've added npm:syncfusion-javascript via JSPM along with this bridge.

Upon running the app JQuery doesn't seem to be imported at any point by the bridge and doesn't end up loading in the browser.  Also I'll note when I include the bridge components in a JSPM bundle, JQuery is not included as a dependency.

Rolling the version back to 1.2 fixes everything.

Browser error:
ReferenceError: jQuery is not defined
    at ejMaskEdit.createWidget (widget-base.js:60)

**Comment by karthickthangasamy** [comment]
@MrRobboto We made breaking changes to optimise the bundling process, In which we have to refer the `syncfusion-javascript` widget in sample to overcome this issue. Refer to the below link for detailed information.

https://help.syncfusion.com/aurelia/release-notes/v15.4.0.17?type=all#common-breaking-changes

Since, you have to import the `ej.maskedit.min` in sample to resolve the issue.
```
import 'syncfusion-javascript/Scripts/ej/web/ej.maskedit.min';
```

Refer to the below link for integrating `aurelia-syncfusion-bridge` and `syncfusion-javascript` into `aurelia-skeletons`.

https://help.syncfusion.com/aurelia/getting-started/skeleton-typescript

Thanks,
Karthick T

**Comment by MrRobboto** [comment]
Ah, that's actually a lot nicer!  Just needed to know what to change and couldn't find the docs provided.  Thank you very much for the quick response!  Took me awhile to figure out it was the bridge and killed 2 hours but it was my fault I accidentally upgraded...

Thanks again,
Rob

**Comment by karthickthangasamy** [comment]
@MrRobboto Thanks for your feedback. 

I have updated the GitHub release with release notes information [here](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/releases/tag/2.2.0).

If you have any queries/concerns let me know, I will always here to assist you.

Thanks.!
